on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

  push:
    branches:
      - 'master'
    paths:
      - 'run.js'

jobs:
  run-node:
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore BMI cache
        id: cache-bmi
        uses: actions/cache@v4
        with:
          path: bmi
          key: bmi

      - name: Clone BMI
        if: steps.cache-bmi.outputs.cache-hit == ''
        run: |
          git clone https://github.com/skyline69/balatro-mod-index.git bmi

      - name: Pull BMI
        if: steps.cache-bmi.outputs.cache-hit != ''
        run: |
          cd bmi
          git restore .
          git pull origin main
          cd ..

      - name: Clear BMI
        run: |
          cd bmi
          rm mods/**/*.jpg
          cd ..

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Nodejs setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          node run

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.TOKEN }}
